In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
import pandas as pd

df = pd.read_csv("/content/drive/MyDrive/데이터마이닝/train.csv")
test = pd.read_csv("/content/drive/MyDrive/데이터마이닝/test.csv")

In [ ]:
df.head()

,id,base_date,day_of_week,base_hour,lane_count,road_rating,road_name,multi_linked,connect_code,maximum_speed_limit,...,road_type,start_node_name,start_latitude,start_longitude,start_turn_restricted,end_node_name,end_latitude,end_longitude,end_turn_restricted,target
0,TRAIN_0000000,20220623,목,17,1,106,지방도1112호선,0,0,60.0,...,3,제3교래교,33.427747,126.662612,없음,제3교래교,33.427749,126.662335,없음,52.0
1,TRAIN_0000001,20220728,목,21,2,103,일반국도11호선,0,0,60.0,...,0,광양사거리,33.500730,126.529107,있음,KAL사거리,33.504811,126.526240,없음,30.0
2,TRAIN_0000002,20211010,일,7,2,103,일반국도16호선,0,0,80.0,...,0,창고천교,33.279145,126.368598,없음,상창육교,33.280072,126.362147,없음,61.0
3,TRAIN_0000003,20220311,금,13,2,107,태평로,0,0,50.0,...,0,남양리조트,33.246081,126.567204,없음,서현주택,33.245565,126.566228,없음,20.0
4,TRAIN_0000004,20211005,화,8,2,103,일반국도12호선,0,0,80.0,...,0,애월샷시,33.462214,126.326551,없음,애월입구,33.462677,126.330152,없음,38.0

In [ ]:
df.isnull().sum() # 결측치 확인

id                       0
base_date                0
day_of_week              0
base_hour                0
lane_count               0
road_rating              0
road_name                0
multi_linked             0
connect_code             0
maximum_speed_limit      0
vehicle_restricted       0
weight_restricted        0
height_restricted        0
road_type                0
start_node_name          0
start_latitude           0
start_longitude          0
start_turn_restricted    0
end_node_name            0
end_latitude             0
end_longitude            0
end_turn_restricted      0
target                   0
dtype: int64

In [ ]:
df.info() # object 열 확인 -> 범주형데이터로 수정필요 (+ base_date)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4701217 entries, 0 to 4701216
Data columns (total 23 columns):
 #   Column                 Dtype
---  ------                 -----
 0   id                     object
 1   base_date              int64
 2   day_of_week            object
 3   base_hour              int64
 4   lane_count             int64
 5   road_rating            int64
 6   road_name              object
 7   multi_linked           int64
 8   connect_code           int64
 9   maximum_speed_limit    float64
 10  vehicle_restricted     float64
 11  weight_restricted      float64
 12  height_restricted      float64
 13  road_type              int64
 14  start_node_name        object
 15  start_latitude         float64
 16  start_longitude        float64
 17  start_turn_restricted  object
 18  end_node_name          object
 19  end_latitude           float64
 20  end_longitude          float64
 21  end_turn_restricted    object
 22  target                 float64
dtypes: float64(9), int64(7), object(7)
memory usage: 825.0+ MB

In [ ]:
df = df.drop(['id'], axis=1) # 'id'열 삭제

In [ ]:
dummies = pd.get_dummies(df.start_turn_restricted) # 원핫인코딩 처리
merged = pd.concat([df,dummies], axis='columns')
df = merged
df = df.drop(['start_turn_restricted'], axis=1)
df.rename(columns={'없음':'start_turn_restricted_N','있음':'start_turn_restricted_Y'}, inplace=True)

In [ ]:
dummies = pd.get_dummies(df.end_turn_restricted) # 원핫인코딩 처리
merged = pd.concat([df,dummies], axis='columns')
df = merged
df = df.drop(['end_turn_restricted'], axis=1)
df.rename(columns={'없음':'end_turn_restricted_N','있음':'end_turn_restricted_Y'}, inplace=True)

In [ ]:
df['base_date'] = pd.to_datetime(df['base_date'],format='%Y%m%d') # 날짜 타입 변경

In [ ]:
from sklearn.preprocessing import LabelEncoder # 라벨인코딩

le = LabelEncoder()
le_encoded = le.fit_transform(df.base_date)
new_cat = pd.DataFrame(le_encoded, columns = ['base_date'])
df = df.drop(['base_date'], axis=1)
merged = pd.concat([df,new_cat], axis='columns')
df = merged

In [ ]:
le = LabelEncoder() # 라벨인코딩
le_encoded = le.fit_transform(df.day_of_week)
new_cat = pd.DataFrame(le_encoded, columns = ['day_of_week'])
df = df.drop(['day_of_week'], axis=1)
merged = pd.concat([df,new_cat], axis='columns')
df = merged

In [ ]:
le = LabelEncoder() # 라벨인코딩
le_encoded = le.fit_transform(df.road_name)
new_cat = pd.DataFrame(le_encoded, columns = ['road_name'])
df = df.drop(['road_name'], axis=1)
merged = pd.concat([df,new_cat], axis='columns')
df = merged
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4701217 entries, 0 to 4701216
Data columns (total 24 columns):
 #   Column                   Dtype
---  ------                   -----
 0   base_hour                int64
 1   lane_count               int64
 2   road_rating              int64
 3   multi_linked             int64
 4   connect_code             int64
 5   maximum_speed_limit      float64
 6   vehicle_restricted       float64
 7   weight_restricted        float64
 8   height_restricted        float64
 9   road_type                int64
 10  start_node_name          object
 11  start_latitude           float64
 12  start_longitude          float64
 13  end_node_name            object
 14  end_latitude             float64
 15  end_longitude            float64
 16  target                   float64
 17  start_turn_restricted_N  uint8
 18  start_turn_restricted_Y  uint8
 19  end_turn_restricted_N    uint8
 20  end_turn_restricted_Y    uint8
 21  base_date                int64
 22  day_of_week              int64
 23  road_name                int64
dtypes: float64(9), int64(9), object(2), uint8(4)
memory usage: 735.3+ MB

In [ ]:
le = LabelEncoder() # 라벨인코딩
le_encoded = le.fit_transform(df.start_node_name)
new_cat = pd.DataFrame(le_encoded, columns = ['start_node_name'])
df = df.drop(['start_node_name'], axis=1)
merged = pd.concat([df,new_cat], axis='columns')
df = merged
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4701217 entries, 0 to 4701216
Data columns (total 24 columns):
 #   Column                   Dtype
---  ------                   -----
 0   base_hour                int64
 1   lane_count               int64
 2   road_rating              int64
 3   multi_linked             int64
 4   connect_code             int64
 5   maximum_speed_limit      float64
 6   vehicle_restricted       float64
 7   weight_restricted        float64
 8   height_restricted        float64
 9   road_type                int64
 10  start_latitude           float64
 11  start_longitude          float64
 12  end_node_name            object
 13  end_latitude             float64
 14  end_longitude            float64
 15  target                   float64
 16  start_turn_restricted_N  uint8
 17  start_turn_restricted_Y  uint8
 18  end_turn_restricted_N    uint8
 19  end_turn_restricted_Y    uint8
 20  base_date                int64
 21  day_of_week              int64
 22  road_name                int64
 23  start_node_name          int64
dtypes: float64(9), int64(10), object(1), uint8(4)
memory usage: 735.3+ MB

In [ ]:
le = LabelEncoder() # 라벨인코딩
le_encoded = le.fit_transform(df.end_node_name)
new_cat = pd.DataFrame(le_encoded, columns = ['end_node_name'])
df = df.drop(['end_node_name'], axis=1)
merged = pd.concat([df,new_cat], axis='columns')
df = merged
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4701217 entries, 0 to 4701216
Data columns (total 24 columns):
 #   Column                   Dtype
---  ------                   -----
 0   base_hour                int64
 1   lane_count               int64
 2   road_rating              int64
 3   multi_linked             int64
 4   connect_code             int64
 5   maximum_speed_limit      float64
 6   vehicle_restricted       float64
 7   weight_restricted        float64
 8   height_restricted        float64
 9   road_type                int64
 10  start_latitude           float64
 11  start_longitude          float64
 12  end_latitude             float64
 13  end_longitude            float64
 14  target                   float64
 15  start_turn_restricted_N  uint8
 16  start_turn_restricted_Y  uint8
 17  end_turn_restricted_N    uint8
 18  end_turn_restricted_Y    uint8
 19  base_date                int64
 20  day_of_week              int64
 21  road_name                int64
 22  start_node_name          int64
 23  end_node_name            int64
dtypes: float64(9), int64(11), uint8(4)
memory usage: 735.3 MB

In [ ]:
df['target'] = pd.cut(df.target, bins=[0,41.1,113], labels=[1,0]) # 종속변수 0,1로 바꿈

In [ ]:
x = df.drop('target', axis=1) # x:독립변수, y:종속변수
y = df['target']

In [ ]:
from sklearn.preprocessing import MinMaxScaler # 독립변수 min-max scaling

scaler = MinMaxScaler()
x_scaler = scaler.fit_transform(x)
x_scaler = pd.DataFrame(x_scaler, columns = x.columns)
x_scaler

,base_hour,lane_count,road_rating,multi_linked,connect_code,maximum_speed_limit,vehicle_restricted,weight_restricted,height_restricted,road_type,...,end_longitude,start_turn_restricted_N,start_turn_restricted_Y,end_turn_restricted_N,end_turn_restricted_Y,base_date,day_of_week,road_name,start_node_name,end_node_name
0,0.739130,0.0,0.75,0.0,0.0,0.6,0.0,0.648,0.0,1.0,...,0.641057,1.0,0.0,1.0,0.0,0.864286,0.166667,0.766667,0.794239,0.794239
1,0.913043,0.5,0.00,0.0,0.0,0.6,0.0,0.000,0.0,0.0,...,0.459191,0.0,1.0,1.0,0.0,0.989286,0.166667,0.566667,0.065844,0.004115
2,0.304348,0.5,0.00,0.0,0.0,1.0,0.0,0.000,0.0,0.0,...,0.239911,1.0,0.0,1.0,0.0,0.139286,0.666667,0.600000,0.876543,0.368313
3,0.565217,0.5,1.00,0.0,0.0,0.4,0.0,0.000,0.0,0.0,...,0.512628,1.0,0.0,1.0,0.0,0.600000,0.000000,0.950000,0.119342,0.417695
4,0.347826,0.5,0.00,0.0,0.0,1.0,0.0,0.000,0.0,0.0,...,0.197154,1.0,0.0,1.0,0.0,0.121429,1.000000,0.583333,0.549383,0.553498
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4701212,0.695652,0.0,1.00,0.0,0.0,0.4,0.0,0.000,0.0,0.0,...,0.121783,1.0,0.0,1.0,0.0,0.228571,0.166667,0.000000,0.162551,0.086420
4701213,0.086957,0.5,1.00,0.0,0.0,1.0,0.0,0.864,0.0,1.0,...,0.323755,1.0,0.0,1.0,0.0,0.671429,0.166667,0.000000,0.063786,0.063786
4701214,0.956522,0.5,0.00,0.0,0.0,0.6,0.0,0.000,0.0,0.0,...,0.975955,1.0,0.0,1.0,0.0,0.828571,0.500000,0.583333,0.039095,0.440329
4701215,0.086957,0.5,0.00,0.0,0.0,1.0,0.0,0.000,0.0,0.0,...,0.335035,1.0,0.0,1.0,0.0,0.175000,0.333333,0.616667,0.806584,0.047325
4701216,0.260870,0.5,1.00,0.0,0.0,0.6,0.0,0.000,0.0,0.0,...,0.437975,1.0,0.0,1.0,0.0,0.171429,1.000000,0.016667,0.390947,0.508230

In [ ]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x_scaler, y, test_size = 0.2, random_state = 0)

Decision tree

In [ ]:
from sklearn.tree import DecisionTreeClassifier

dt = DecisionTreeClassifier(max_depth=5, random_state=0)

dt.fit(x_train, y_train)

pred = dt.predict(x_test)

In [ ]:
from sklearn.metrics import accuracy_score
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn.metrics import f1_score

print("Accuracy: ", accuracy_score(y_test,pred))
print("Precision: ", precision_score(y_test,pred))
print("Recall: ", recall_score(y_test,pred))
print("F1: ", f1_score(y_test,pred))

In [ ]:
# feature importance 확인
import eli5
from eli5.sklearn import PermutationImportance

perm = PermutationImportance(dt, random_state=0).fit(x_test, y_test)
eli5.show_weights(perm, feature_names = x_test.columns.tolist())

RandomForestClassifier

In [ ]:
from sklearn.ensemble import RandomForestClassifier

rf = RandomForestClassifier(max_depth = 10, n_estimators = 100, max_features = 5)

rf.fit(x_train, y_train)

pred = rf.predict(x_test)

In [ ]:
from sklearn.metrics import accuracy_score
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn.metrics import f1_score

print("Accuracy: ", accuracy_score(y_test,pred))
print("Precision: ", precision_score(y_test,pred))
print("Recall: ", recall_score(y_test,pred))
print("F1: ", f1_score(y_test,pred))

In [ ]:
# feature importance 확인
import eli5
from eli5.sklearn import PermutationImportance

perm = PermutationImportance(rf, random_state=0).fit(x_test, y_test)
eli5.show_weights(perm, feature_names = x_test.columns.tolist())

GradientBoostingClassifier

In [ ]:
from sklearn.ensemble import GradientBoostingClassifier

GB = GradientBoostingClassifier(learning_rate=0.1, max_depth=3, min_samples_split=5,n_estimators=75, random_state=1)

GB.fit(x_train, y_train)

pred = GB.predict(x_test)

In [ ]:
from sklearn.metrics import accuracy_score
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn.metrics import f1_score

print("Accuracy: ", accuracy_score(y_test,pred))
print("Precision: ", precision_score(y_test,pred))
print("Recall: ", recall_score(y_test,pred))
print("F1: ", f1_score(y_test,pred))

In [ ]:
# feature importance 확인
import eli5
from eli5.sklearn import PermutationImportance

perm = PermutationImportance(GB, random_state=0).fit(x_test, y_test)
eli5.show_weights(perm, feature_names = x_test.columns.tolist())

XGBoostClassifier

In [ ]:
from xgboost import XGBClassifier

xgb = XGBClassifier(tree_method = 'exact',learning_rate=0.03, n_estimators=400,
                    max_depth=6,max_leaves = 63, random_state=0, colsample_bytree =  0.3)

xgb.fit(x_train, y_train)

pred = xgb.predict(x_test)

In [ ]:
from sklearn.metrics import accuracy_score
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn.metrics import f1_score

print("Accuracy: ", accuracy_score(y_test,pred))
print("Precision: ", precision_score(y_test,pred))
print("Recall: ", recall_score(y_test,pred))
print("F1: ", f1_score(y_test,pred))

In [ ]:
# feature importance 확인
import eli5
from eli5.sklearn import PermutationImportance

perm = PermutationImportance(xgb, random_state=0).fit(x_test, y_test)
eli5.show_weights(perm, feature_names = x_test.columns.tolist())

LightGBMClassifier

In [ ]:
from lightgbm import LGBMClassifier

LGBM = LGBMClassifier(min_data_in_leaf=10, max_depth=-1, num_leaves = 31, random_state=1, learning_rate = 0.04)

LGBM.fit(x_train, y_train)

pred = LGBM.predict(x_test)

In [ ]:
from sklearn.metrics import accuracy_score
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn.metrics import f1_score

print("Accuracy: ", accuracy_score(y_test,pred))
print("Precision: ", precision_score(y_test,pred))
print("Recall: ", recall_score(y_test,pred))
print("F1: ", f1_score(y_test,pred))

Accuracy:  0.8986475850949328
Precision:  0.896018456197126
Recall:  0.8889073744747533
F1:  0.8924487501862193

In [ ]:
pip install eli5

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting eli5
  Downloading eli5-0.13.0.tar.gz (216 kB)
     |████████████████████████████████| 216 kB 5.2 MB/s
Requirement already satisfied: attrs>17.1.0 in /usr/local/lib/python3.7/dist-packages (from eli5) (22.1.0)
Collecting jinja2>=3.0.0
  Downloading Jinja2-3.1.2-py3-none-any.whl (133 kB)
     |████████████████████████████████| 133 kB 49.8 MB/s
Requirement already satisfied: numpy>=1.9.0 in /usr/local/lib/python3.7/dist-packages (from eli5) (1.21.6)
Requirement already satisfied: scipy in /usr/local/lib/python3.7/dist-packages (from eli5) (1.7.3)
Requirement already satisfied: six in /usr/local/lib/python3.7/dist-packages (from eli5) (1.15.0)
Requirement already satisfied: scikit-learn>=0.20 in /usr/local/lib/python3.7/dist-packages (from eli5) (1.0.2)
Requirement already satisfied: graphviz in /usr/local/lib/python3.7/dist-packages (from eli5) (0.10.1)
Requirement already satisfied: tabulate>=0.7.7 in /usr/local/lib/python3.7/dist-packages (from eli5) (0.8.10)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.7/dist-packages (from jinja2>=3.0.0->eli5) (2.0.1)
Requirement already satisfied: threadpoolctl>=2.0.0 in /usr/local/lib/python3.7/dist-packages (from scikit-learn>=0.20->eli5) (3.1.0)
Requirement already satisfied: joblib>=0.11 in /usr/local/lib/python3.7/dist-packages (from scikit-learn>=0.20->eli5) (1.2.0)
Building wheels for collected packages: eli5
  Building wheel for eli5 (setup.py) ... done
  Created wheel for eli5: filename=eli5-0.13.0-py2.py3-none-any.whl size=107748 sha256=4f893df200146d87f64310c865b49050acaa80560de90ce8e17ae6613304ac0c
  Stored in directory: /root/.cache/pip/wheels/cc/3c/96/3ead31a8e6c20fc0f1a707fde2e05d49a80b1b4b30096573be
Successfully built eli5
Installing collected packages: jinja2, eli5
  Attempting uninstall: jinja2
    Found existing installation: Jinja2 2.11.3
    Uninstalling Jinja2-2.11.3:
      Successfully uninstalled Jinja2-2.11.3
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
notebook 5.7.16 requires jinja2<=3.0.0, but you have jinja2 3.1.2 which is incompatible.
flask 1.1.4 requires Jinja2<3.0,>=2.10.1, but you have jinja2 3.1.2 which is incompatible.
Successfully installed eli5-0.13.0 jinja2-3.1.2

In [ ]:
# feature importance 확인
import eli5
from eli5.sklearn import PermutationImportance

perm = PermutationImportance(LGBM, random_state=0).fit(x_test, y_test)
eli5.show_weights(perm, feature_names = x_test.columns.tolist())

CatBoostClassifier

In [ ]:
from catboost import CatBoostClassifier

CB = CatBoostClassifier(iterations=2, depth=3, learning_rate=1, loss_function='Logloss', verbose=True)

CB.fit(x_train, y_train)

pred = CB.predict(x_test)

In [ ]:
from sklearn.metrics import accuracy_score
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn.metrics import f1_score

print("Accuracy: ", accuracy_score(y_test,pred))
print("Precision: ", precision_score(y_test,pred))
print("Recall: ", recall_score(y_test,pred))
print("F1: ", f1_score(y_test,pred))

In [ ]:
# feature importance 확인
import eli5
from eli5.sklearn import PermutationImportance

perm = PermutationImportance(CB, random_state=0).fit(x_test, y_test)
eli5.show_weights(perm, feature_names = x_test.columns.tolist())

Neural Network

In [ ]:
from sklearn.neural_network import MLPClassifier
Neural = MLPClassifier(solver = "lbfgs", alpha = 1e-5, hidden_layer_sizes = (5,2), random_state = 1)

Neural.fit(x_train, y_train)

pred = Neural.predict(x_test)

In [ ]:
from sklearn.metrics import accuracy_score
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn.metrics import f1_score

print("Accuracy: ", accuracy_score(y_test,pred))
print("Precision: ", precision_score(y_test,pred))
print("Recall: ", recall_score(y_test,pred))
print("F1: ", f1_score(y_test,pred))

In [ ]:
#feature importance 확인

import eli5
from eli5.sklearn import PermutationImportance

perm = PermutationImportance(Neural, random_state = 0).fit(x_test, y_test)
eli5.show_weights(perm,feature_names=x_test.columns.tolist())